---
title: "Final Project Data Memo"
author: "Jules Merigot (8488256)"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r setup, echo=FALSE, include=FALSE}
library(knitr)
# set global chunk options: images will be 7x5 inches
knitr::opts_chunk$set(fig.width=7, fig.height=5)
options(digits = 4)

## indents are for indenting r code as formatted text
## They may need to be adjusted depending on your OS
# if your output looks odd, increase or decrease indent
indent1 = '    '
indent2 = '        '
indent3 = '            '
```

## Dataset Overview

The dataset includes data about the United States electric power industry estimated emissions by state from 1990 to 2020. The emissions data is on the metric tons of CO2, SO2, and NOx released each year, categorized by state, producer type, and energy source.   
I will be obtaining the dataset from the U.S. Energy Information Administration website, which can be found here: https://www.eia.gov/electricity/data.php#elecenv. I will be downloading the dataset as an XLS file.   
There are 44,747 observations and 7 predictors. The variables I will be working with are the metric tons of CO2, SO2, and NOx being emitted, the year, the state, the producer type, and the energy source causing the emissions. There is no missing data.

## Research Question(s) Overview

Based on the data from the dataset, I am interested in predicting U.S. carbon dioxode emissions for future years to come. Additionally, I am interested in discovering what the U.S. carbon budget is at any given point in time with the goal to avoid the carbon emissions beyond a limit resulting in rise of global temperature by 1.5 deg or so.   
My most important and most useful response/outcome variables will be mainly the metric tons of CO2 emissions, with SO2 and NOx emissions being secondary exploratory variables. These variables are the amount of metric tons of a particular gas emitted by each state by a specific energy source, such as coal or petroleum.   
I believe these questions will be best answered by a regression approach so that I can model the emissions of future years.   
The goal of my model is mainly predictive because I am trying to discover what future emissions may look like, but it may also be descriptive as I try to create a visual to educate my community on the dangers of carbon dioxide emissions.

## Proposed Project Timeline

I plan on having my data loaded by the beginning of next week, with a start to my explanatory analysis taking place next weekend. I am going to set a week-by-week deadline for myself to work on my project. Deadlines will include sections of my project such data cleaning, model training, model making, etc.

## Questions and Concerns

I do have some concerns about this project. I struggled to find a dataset and project idea that I was happy with and spent many hours searching the internet. I am a big environmental activist and I knew that I wanted to do my project on something related to climate change. I would prefer this than a simpler project that I find less interesting. However, I am afraid that anything related to climate change predictions may be too difficult, or too complicated if it isn't very specific.    
Additionally, I am afraid that my dataset that I picked may not be the best because it lacks heavily in variables, which would restrict my prediction possibilities. I would love some advice on this since I want this project to be a success and something I could showcase on my resume later on.
