---
title: "Homework 2"
author: "Jules Merigot (8488256)"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, echo=FALSE, include=FALSE}
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(ISLR)
library(corrplot)
library(ggthemes)
tidymodels_prefer()

library(knitr)
# set global chunk options: images will be 7x5 inches
knitr::opts_chunk$set(fig.width=7, fig.height=5)
options(digits = 4)

## indents are for indenting r code as formatted text
## They may need to be adjusted depending on your OS
# if your output looks odd, increase or decrease indent
indent1 = '    '
indent2 = '        '
indent3 = '            '

aba_data <- read.csv(file = "C:/Users/jules/OneDrive/Desktop/PSTAT-131/data/abalone.csv")
```

\begin{center}
PSTAT 131/231 Statistical Machine Learning - Fall 2022
\end{center}

# Linear Regression

## Question 1

```{r}
# Adding the age variable as a column to the Abalone data frame
abalones <- aba_data %>%
  mutate(age = rings + 1.5)

# Checking to see it was correctly added
head(abalones)

# Making a histogram of the age in order to asses the distribution
hist(abalones$age)
```

Using a histogram, we can see that the age of the abalones is normally distributed and skewed right, with an average age of about 11 years old. While there are more outliers that are older in age, most abalones tend to live between 5 and 15 years.

## Question 2

```{r}
set.seed(52746)

aba_split <- initial_split(abalones, prop=0.80, strata=age)

aba_train <- training(aba_split)
aba_test <- testing(aba_split)
```